/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecyclerRouteImport } from './routes/recycler'
import { Route as ManufacturerRouteImport } from './routes/manufacturer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsumerRouteImport } from './routes/consumer'
import { Route as CollectorRouteImport } from './routes/collector'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JourneyItemIdRouteImport } from './routes/journey.$itemId'
import { Route as DashboardQueueRouteImport } from './routes/dashboard.queue'
import { Route as DashboardPickupsRouteImport } from './routes/dashboard.pickups'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard.inventory'

const RecyclerRoute = RecyclerRouteImport.update({
  id: '/recycler',
  path: '/recycler',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturerRoute = ManufacturerRouteImport.update({
  id: '/manufacturer',
  path: '/manufacturer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerRoute = ConsumerRouteImport.update({
  id: '/consumer',
  path: '/consumer',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorRoute = CollectorRouteImport.update({
  id: '/collector',
  path: '/collector',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyItemIdRoute = JourneyItemIdRouteImport.update({
  id: '/journey/$itemId',
  path: '/journey/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardQueueRoute = DashboardQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPickupsRoute = DashboardPickupsRouteImport.update({
  id: '/pickups',
  path: '/pickups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collector': typeof CollectorRoute
  '/consumer': typeof ConsumerRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/manufacturer': typeof ManufacturerRoute
  '/recycler': typeof RecyclerRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/pickups': typeof DashboardPickupsRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/journey/$itemId': typeof JourneyItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collector': typeof CollectorRoute
  '/consumer': typeof ConsumerRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/manufacturer': typeof ManufacturerRoute
  '/recycler': typeof RecyclerRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/pickups': typeof DashboardPickupsRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/journey/$itemId': typeof JourneyItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collector': typeof CollectorRoute
  '/consumer': typeof ConsumerRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/manufacturer': typeof ManufacturerRoute
  '/recycler': typeof RecyclerRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/pickups': typeof DashboardPickupsRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/journey/$itemId': typeof JourneyItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collector'
    | '/consumer'
    | '/dashboard'
    | '/manufacturer'
    | '/recycler'
    | '/dashboard/inventory'
    | '/dashboard/pickups'
    | '/dashboard/queue'
    | '/journey/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collector'
    | '/consumer'
    | '/dashboard'
    | '/manufacturer'
    | '/recycler'
    | '/dashboard/inventory'
    | '/dashboard/pickups'
    | '/dashboard/queue'
    | '/journey/$itemId'
  id:
    | '__root__'
    | '/'
    | '/collector'
    | '/consumer'
    | '/dashboard'
    | '/manufacturer'
    | '/recycler'
    | '/dashboard/inventory'
    | '/dashboard/pickups'
    | '/dashboard/queue'
    | '/journey/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectorRoute: typeof CollectorRoute
  ConsumerRoute: typeof ConsumerRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ManufacturerRoute: typeof ManufacturerRoute
  RecyclerRoute: typeof RecyclerRoute
  JourneyItemIdRoute: typeof JourneyItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recycler': {
      id: '/recycler'
      path: '/recycler'
      fullPath: '/recycler'
      preLoaderRoute: typeof RecyclerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturer': {
      id: '/manufacturer'
      path: '/manufacturer'
      fullPath: '/manufacturer'
      preLoaderRoute: typeof ManufacturerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer': {
      id: '/consumer'
      path: '/consumer'
      fullPath: '/consumer'
      preLoaderRoute: typeof ConsumerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector': {
      id: '/collector'
      path: '/collector'
      fullPath: '/collector'
      preLoaderRoute: typeof CollectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/$itemId': {
      id: '/journey/$itemId'
      path: '/journey/$itemId'
      fullPath: '/journey/$itemId'
      preLoaderRoute: typeof JourneyItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/queue': {
      id: '/dashboard/queue'
      path: '/queue'
      fullPath: '/dashboard/queue'
      preLoaderRoute: typeof DashboardQueueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pickups': {
      id: '/dashboard/pickups'
      path: '/pickups'
      fullPath: '/dashboard/pickups'
      preLoaderRoute: typeof DashboardPickupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardPickupsRoute: typeof DashboardPickupsRoute
  DashboardQueueRoute: typeof DashboardQueueRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardPickupsRoute: DashboardPickupsRoute,
  DashboardQueueRoute: DashboardQueueRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectorRoute: CollectorRoute,
  ConsumerRoute: ConsumerRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ManufacturerRoute: ManufacturerRoute,
  RecyclerRoute: RecyclerRoute,
  JourneyItemIdRoute: JourneyItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
